/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define FEMTOHTTP_STABILITY "___dtrace_stability$femtohttp$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define FEMTOHTTP_TYPEDEFS "___dtrace_typedefs$femtohttp$v1"

#define	FEMTOHTTP_HOST_CLOSE_CONNECTION(arg0, arg1, arg2, arg3, arg4) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__close__connection$v1$696e74$63686172202a$696e74$696e74$696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_CLOSE_CONNECTION_ENABLED() \
	__dtrace_isenabled$femtohttp$host__close__connection$v1()
#define	FEMTOHTTP_HOST_KILLED_IDLE(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__killed__idle$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_KILLED_IDLE_ENABLED() \
	__dtrace_isenabled$femtohttp$host__killed__idle$v1()
#define	FEMTOHTTP_HOST_NEW_CONNECTION(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__new__connection$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_NEW_CONNECTION_ENABLED() \
	__dtrace_isenabled$femtohttp$host__new__connection$v1()
#define	FEMTOHTTP_HOST_NEW_FAILED(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__new__failed$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_NEW_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$host__new__failed$v1()
#define	FEMTOHTTP_HOST_OBTAIN_CONNECTION(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__obtain__connection$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_OBTAIN_CONNECTION_ENABLED() \
	__dtrace_isenabled$femtohttp$host__obtain__connection$v1()
#define	FEMTOHTTP_HOST_PRE_WAIT_FOR_SOCKET(arg0, arg1) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__pre__wait__for__socket$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_PRE_WAIT_FOR_SOCKET_ENABLED() \
	__dtrace_isenabled$femtohttp$host__pre__wait__for__socket$v1()
#define	FEMTOHTTP_HOST_WAIT_FOR_SOCKET(arg0, arg1) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$host__wait__for__socket$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOST_WAIT_FOR_SOCKET_ENABLED() \
	__dtrace_isenabled$femtohttp$host__wait__for__socket$v1()
#define	FEMTOHTTP_HOSTPOOL_ADDED(arg0, arg1) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$hostpool__added$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HOSTPOOL_ADDED_ENABLED() \
	__dtrace_isenabled$femtohttp$hostpool__added$v1()
#define	FEMTOHTTP_HTTP_BEGIN(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__begin$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_BEGIN_ENABLED() \
	__dtrace_isenabled$femtohttp$http__begin$v1()
#define	FEMTOHTTP_HTTP_CONTENT_CHUNK(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__content__chunk$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_CONTENT_CHUNK_ENABLED() \
	__dtrace_isenabled$femtohttp$http__content__chunk$v1()
#define	FEMTOHTTP_HTTP_CONTENT_READ(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__content__read$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_CONTENT_READ_ENABLED() \
	__dtrace_isenabled$femtohttp$http__content__read$v1()
#define	FEMTOHTTP_HTTP_CONTENT_READ_DATA(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__content__read__data$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_CONTENT_READ_DATA_ENABLED() \
	__dtrace_isenabled$femtohttp$http__content__read__data$v1()
#define	FEMTOHTTP_HTTP_CONTENT_WRITE(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__content__write$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_CONTENT_WRITE_ENABLED() \
	__dtrace_isenabled$femtohttp$http__content__write$v1()
#define	FEMTOHTTP_HTTP_CONTENT_WRITE_DATA(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__content__write__data$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_CONTENT_WRITE_DATA_ENABLED() \
	__dtrace_isenabled$femtohttp$http__content__write__data$v1()
#define	FEMTOHTTP_HTTP_END() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__end$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_END_ENABLED() \
	__dtrace_isenabled$femtohttp$http__end$v1()
#define	FEMTOHTTP_HTTP_HEADER_READ(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__header__read$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_HEADER_READ_ENABLED() \
	__dtrace_isenabled$femtohttp$http__header__read$v1()
#define	FEMTOHTTP_HTTP_HEADER_READ_DATA(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__header__read__data$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_HEADER_READ_DATA_ENABLED() \
	__dtrace_isenabled$femtohttp$http__header__read__data$v1()
#define	FEMTOHTTP_HTTP_HEADER_STATUS_CODE(arg0, arg1) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__header__status__code$v1$696e74$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_HEADER_STATUS_CODE_ENABLED() \
	__dtrace_isenabled$femtohttp$http__header__status__code$v1()
#define	FEMTOHTTP_HTTP_HEADER_WRITE(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__header__write$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_HEADER_WRITE_ENABLED() \
	__dtrace_isenabled$femtohttp$http__header__write$v1()
#define	FEMTOHTTP_HTTP_HEADER_WRITE_DATA(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__header__write__data$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_HEADER_WRITE_DATA_ENABLED() \
	__dtrace_isenabled$femtohttp$http__header__write__data$v1()
#define	FEMTOHTTP_HTTP_PRE_CONTENT_CHUNK() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__pre__content__chunk$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_PRE_CONTENT_CHUNK_ENABLED() \
	__dtrace_isenabled$femtohttp$http__pre__content__chunk$v1()
#define	FEMTOHTTP_HTTP_PRE_CONTENT_READ(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__pre__content__read$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_PRE_CONTENT_READ_ENABLED() \
	__dtrace_isenabled$femtohttp$http__pre__content__read$v1()
#define	FEMTOHTTP_HTTP_PRE_CONTENT_WRITE(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__pre__content__write$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_PRE_CONTENT_WRITE_ENABLED() \
	__dtrace_isenabled$femtohttp$http__pre__content__write$v1()
#define	FEMTOHTTP_HTTP_PRE_HEADER_READ() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__pre__header__read$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_PRE_HEADER_READ_ENABLED() \
	__dtrace_isenabled$femtohttp$http__pre__header__read$v1()
#define	FEMTOHTTP_HTTP_PRE_HEADER_WRITE(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__pre__header__write$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_PRE_HEADER_WRITE_ENABLED() \
	__dtrace_isenabled$femtohttp$http__pre__header__write$v1()
#define	FEMTOHTTP_HTTP_REDIRECT(arg0, arg1) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__redirect$v1$696e74$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_REDIRECT_ENABLED() \
	__dtrace_isenabled$femtohttp$http__redirect$v1()
#define	FEMTOHTTP_HTTP_SOCKET_AGGRESSIVE_RETRY() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__socket__aggressive__retry$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_SOCKET_AGGRESSIVE_RETRY_ENABLED() \
	__dtrace_isenabled$femtohttp$http__socket__aggressive__retry$v1()
#define	FEMTOHTTP_HTTP_SOCKET_RETRY() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__socket__retry$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_SOCKET_RETRY_ENABLED() \
	__dtrace_isenabled$femtohttp$http__socket__retry$v1()
#define	FEMTOHTTP_HTTP_USING_SOCKET(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$http__using__socket$v1$696e74(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_HTTP_USING_SOCKET_ENABLED() \
	__dtrace_isenabled$femtohttp$http__using__socket$v1()
#define	FEMTOHTTP_RESPONSE_AUTO_DECOMPRESS() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$response__auto__decompress$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_RESPONSE_AUTO_DECOMPRESS_ENABLED() \
	__dtrace_isenabled$femtohttp$response__auto__decompress$v1()
#define	FEMTOHTTP_RESPONSE_DECOMPRESS(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$response__decompress$v1$696e74$696e74$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_RESPONSE_DECOMPRESS_ENABLED() \
	__dtrace_isenabled$femtohttp$response__decompress$v1()
#define	FEMTOHTTP_RESPONSE_PRE_DECOMPRESS() \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$response__pre__decompress$v1(); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_RESPONSE_PRE_DECOMPRESS_ENABLED() \
	__dtrace_isenabled$femtohttp$response__pre__decompress$v1()
#define	FEMTOHTTP_SOCKET_CLOSE(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__close$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_CLOSE_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__close$v1()
#define	FEMTOHTTP_SOCKET_CONNECT_FAILED(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__connect__failed$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_CONNECT_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__connect__failed$v1()
#define	FEMTOHTTP_SOCKET_HOSTNAME_LOOKUP(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__hostname__lookup$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_HOSTNAME_LOOKUP_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__hostname__lookup$v1()
#define	FEMTOHTTP_SOCKET_HOSTNAME_LOOKUP_FAILED(arg0, arg1) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__hostname__lookup__failed$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_HOSTNAME_LOOKUP_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__hostname__lookup__failed$v1()
#define	FEMTOHTTP_SOCKET_OPEN(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__open$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_OPEN_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__open$v1()
#define	FEMTOHTTP_SOCKET_OPEN_FAILED(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__open__failed$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_OPEN_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__open__failed$v1()
#define	FEMTOHTTP_SOCKET_PRE_HOSTNAME_LOOKUP(arg0) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__pre__hostname__lookup$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_PRE_HOSTNAME_LOOKUP_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__pre__hostname__lookup$v1()
#define	FEMTOHTTP_SOCKET_PRE_OPEN(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__pre__open$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_PRE_OPEN_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__pre__open$v1()
#define	FEMTOHTTP_SOCKET_PRE_QUERYSTATUS(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__pre__querystatus$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_PRE_QUERYSTATUS_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__pre__querystatus$v1()
#define	FEMTOHTTP_SOCKET_PRE_READCHUNK(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__pre__readchunk$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_PRE_READCHUNK_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__pre__readchunk$v1()
#define	FEMTOHTTP_SOCKET_PRE_WAITUNTILDATAPRESENT(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__pre__waituntildatapresent$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_PRE_WAITUNTILDATAPRESENT_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__pre__waituntildatapresent$v1()
#define	FEMTOHTTP_SOCKET_PRE_WRITECHUNK(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__pre__writechunk$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_PRE_WRITECHUNK_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__pre__writechunk$v1()
#define	FEMTOHTTP_SOCKET_QUERYSTATUS(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__querystatus$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_QUERYSTATUS_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__querystatus$v1()
#define	FEMTOHTTP_SOCKET_QUERYSTATUS_FAILED(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__querystatus__failed$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_QUERYSTATUS_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__querystatus__failed$v1()
#define	FEMTOHTTP_SOCKET_READCHUNK(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__readchunk$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_READCHUNK_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__readchunk$v1()
#define	FEMTOHTTP_SOCKET_READCHUNK_FAILED(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__readchunk__failed$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_READCHUNK_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__readchunk__failed$v1()
#define	FEMTOHTTP_SOCKET_WAITUNTILDATAPRESENT(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__waituntildatapresent$v1$696e74$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_WAITUNTILDATAPRESENT_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__waituntildatapresent$v1()
#define	FEMTOHTTP_SOCKET_WAITUNTILDATAPRESENT_FAILED(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__waituntildatapresent__failed$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_WAITUNTILDATAPRESENT_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__waituntildatapresent__failed$v1()
#define	FEMTOHTTP_SOCKET_WRITECHUNK(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__writechunk$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_WRITECHUNK_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__writechunk$v1()
#define	FEMTOHTTP_SOCKET_WRITECHUNK_FAILED(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " FEMTOHTTP_TYPEDEFS); \
	__dtrace_probe$femtohttp$socket__writechunk__failed$v1$696e74$63686172202a$696e74$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " FEMTOHTTP_STABILITY); \
} 
#define	FEMTOHTTP_SOCKET_WRITECHUNK_FAILED_ENABLED() \
	__dtrace_isenabled$femtohttp$socket__writechunk__failed$v1()


extern void __dtrace_probe$femtohttp$host__close__connection$v1$696e74$63686172202a$696e74$696e74$696e74(int, char *, int, int, int);
extern int __dtrace_isenabled$femtohttp$host__close__connection$v1(void);
extern void __dtrace_probe$femtohttp$host__killed__idle$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$host__killed__idle$v1(void);
extern void __dtrace_probe$femtohttp$host__new__connection$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$host__new__connection$v1(void);
extern void __dtrace_probe$femtohttp$host__new__failed$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$host__new__failed$v1(void);
extern void __dtrace_probe$femtohttp$host__obtain__connection$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$host__obtain__connection$v1(void);
extern void __dtrace_probe$femtohttp$host__pre__wait__for__socket$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$femtohttp$host__pre__wait__for__socket$v1(void);
extern void __dtrace_probe$femtohttp$host__wait__for__socket$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$femtohttp$host__wait__for__socket$v1(void);
extern void __dtrace_probe$femtohttp$hostpool__added$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$femtohttp$hostpool__added$v1(void);
extern void __dtrace_probe$femtohttp$http__begin$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$http__begin$v1(void);
extern void __dtrace_probe$femtohttp$http__content__chunk$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__content__chunk$v1(void);
extern void __dtrace_probe$femtohttp$http__content__read$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__content__read$v1(void);
extern void __dtrace_probe$femtohttp$http__content__read__data$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$http__content__read__data$v1(void);
extern void __dtrace_probe$femtohttp$http__content__write$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__content__write$v1(void);
extern void __dtrace_probe$femtohttp$http__content__write__data$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$http__content__write__data$v1(void);
extern void __dtrace_probe$femtohttp$http__end$v1(void);
extern int __dtrace_isenabled$femtohttp$http__end$v1(void);
extern void __dtrace_probe$femtohttp$http__header__read$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__header__read$v1(void);
extern void __dtrace_probe$femtohttp$http__header__read__data$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$http__header__read__data$v1(void);
extern void __dtrace_probe$femtohttp$http__header__status__code$v1$696e74$63686172202a(int, char *);
extern int __dtrace_isenabled$femtohttp$http__header__status__code$v1(void);
extern void __dtrace_probe$femtohttp$http__header__write$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__header__write$v1(void);
extern void __dtrace_probe$femtohttp$http__header__write__data$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$http__header__write__data$v1(void);
extern void __dtrace_probe$femtohttp$http__pre__content__chunk$v1(void);
extern int __dtrace_isenabled$femtohttp$http__pre__content__chunk$v1(void);
extern void __dtrace_probe$femtohttp$http__pre__content__read$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__pre__content__read$v1(void);
extern void __dtrace_probe$femtohttp$http__pre__content__write$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__pre__content__write$v1(void);
extern void __dtrace_probe$femtohttp$http__pre__header__read$v1(void);
extern int __dtrace_isenabled$femtohttp$http__pre__header__read$v1(void);
extern void __dtrace_probe$femtohttp$http__pre__header__write$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__pre__header__write$v1(void);
extern void __dtrace_probe$femtohttp$http__redirect$v1$696e74$63686172202a(int, char *);
extern int __dtrace_isenabled$femtohttp$http__redirect$v1(void);
extern void __dtrace_probe$femtohttp$http__socket__aggressive__retry$v1(void);
extern int __dtrace_isenabled$femtohttp$http__socket__aggressive__retry$v1(void);
extern void __dtrace_probe$femtohttp$http__socket__retry$v1(void);
extern int __dtrace_isenabled$femtohttp$http__socket__retry$v1(void);
extern void __dtrace_probe$femtohttp$http__using__socket$v1$696e74(int);
extern int __dtrace_isenabled$femtohttp$http__using__socket$v1(void);
extern void __dtrace_probe$femtohttp$response__auto__decompress$v1(void);
extern int __dtrace_isenabled$femtohttp$response__auto__decompress$v1(void);
extern void __dtrace_probe$femtohttp$response__decompress$v1$696e74$696e74$696e74(int, int, int);
extern int __dtrace_isenabled$femtohttp$response__decompress$v1(void);
extern void __dtrace_probe$femtohttp$response__pre__decompress$v1(void);
extern int __dtrace_isenabled$femtohttp$response__pre__decompress$v1(void);
extern void __dtrace_probe$femtohttp$socket__close$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__close$v1(void);
extern void __dtrace_probe$femtohttp$socket__connect__failed$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__connect__failed$v1(void);
extern void __dtrace_probe$femtohttp$socket__hostname__lookup$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$socket__hostname__lookup$v1(void);
extern void __dtrace_probe$femtohttp$socket__hostname__lookup__failed$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$femtohttp$socket__hostname__lookup__failed$v1(void);
extern void __dtrace_probe$femtohttp$socket__open$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__open$v1(void);
extern void __dtrace_probe$femtohttp$socket__open__failed$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__open__failed$v1(void);
extern void __dtrace_probe$femtohttp$socket__pre__hostname__lookup$v1$63686172202a(char *);
extern int __dtrace_isenabled$femtohttp$socket__pre__hostname__lookup$v1(void);
extern void __dtrace_probe$femtohttp$socket__pre__open$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__pre__open$v1(void);
extern void __dtrace_probe$femtohttp$socket__pre__querystatus$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__pre__querystatus$v1(void);
extern void __dtrace_probe$femtohttp$socket__pre__readchunk$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__pre__readchunk$v1(void);
extern void __dtrace_probe$femtohttp$socket__pre__waituntildatapresent$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__pre__waituntildatapresent$v1(void);
extern void __dtrace_probe$femtohttp$socket__pre__writechunk$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__pre__writechunk$v1(void);
extern void __dtrace_probe$femtohttp$socket__querystatus$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__querystatus$v1(void);
extern void __dtrace_probe$femtohttp$socket__querystatus__failed$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__querystatus__failed$v1(void);
extern void __dtrace_probe$femtohttp$socket__readchunk$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__readchunk$v1(void);
extern void __dtrace_probe$femtohttp$socket__readchunk__failed$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__readchunk__failed$v1(void);
extern void __dtrace_probe$femtohttp$socket__waituntildatapresent$v1$696e74$63686172202a$696e74(int, char *, int);
extern int __dtrace_isenabled$femtohttp$socket__waituntildatapresent$v1(void);
extern void __dtrace_probe$femtohttp$socket__waituntildatapresent__failed$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__waituntildatapresent__failed$v1(void);
extern void __dtrace_probe$femtohttp$socket__writechunk$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__writechunk$v1(void);
extern void __dtrace_probe$femtohttp$socket__writechunk__failed$v1$696e74$63686172202a$696e74$696e74(int, char *, int, int);
extern int __dtrace_isenabled$femtohttp$socket__writechunk__failed$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
